### ISSUE TITLE
Need some help installing the mods

### ISSUE THREAD

**Issue by szmit1** [JustArion/DeathMustDieMods#1]
im litelarry an idiot and bpnix seems nto working at all  can you do a video tutorial maeby or aready to put in game pack pls?

**Comment by JustArion** [comment]
Hi, submitting an issue for this was a good idea! I'll show some steps which you can do if you want to do it manually and then I'll also upload a game pack for you, if you want to instead just drag and drop everything in 1 go.

Manual way:
1. You should download [BepInEx_UnityMono_x86_6.0.0-pre.1.zip](https://github.com/BepInEx/BepInEx/releases/download/v6.0.0-pre.1/BepInEx_UnityMono_x86_6.0.0-pre.1.zip)
2. Extract the .zip file in your **Death Must Die** game folder (If you right click the game on Steam on your games list, and select "Manage" -> "Browse local files" you should be in the game's folder. Extract everything in the .zip into that folder)
3. Download the mods you want to use in the game.
4. Put the mods in `..\Death Must Die\BepInEx\plugins\` folder

Game pack way:
1. Download [Death Must Die Mod Pack.zip](https://github.com/JustArion/DeathMustDieMods/files/13762951/Death.Must.Die.Mod.Pack.zip)
2. Extract the .zip file in your **Death Must Die** game folder (If you right click the game on Steam on your games list, and select "Manage" -> "Browse local files" you should be in the game's folder. Extract everything in the .zip into that folder)
3. (Optional) Remove any mods you don't want to use from the `\BepInEx\plugins\` folder

Let me know if this worked or you got stuck doing a step and I'll try to help more.

**Comment by szmit1** [comment]
So i downloaded it .   it doenst have plugins folder . i create one and put those mods folder and it doeanst work :_: i will try game pack metode tho
![image](https://github.com/JustArion/DeathMustDieMods/assets/154764420/802b5f3d-7d53-4ab0-980e-f112f358a991)

**Comment by szmit1** [comment]
Also in mod folder originally were 0 dll just those 
![image](https://github.com/JustArion/DeathMustDieMods/assets/154764420/1ff1ee10-3e5c-4f02-a87b-5aaef2f860b8)

**Comment by szmit1** [comment]
![image](https://github.com/JustArion/DeathMustDieMods/assets/154764420/0550ddfe-bccd-4117-924c-66def126feec)
 also idk if its work or not i have 4 stashes from begining with or without modpack
 
![image](https://github.com/JustArion/DeathMustDieMods/assets/154764420/696020a5-cd10-4bc1-9f68-cd19cb38af22)

**Comment by JustArion** [comment]
Oh, you've downloaded the source code not the mod itself 😁
The mod .dlls are available in the [Releases](https://github.com/JustArion/DeathMustDieMods/releases/latest) section.

From the .zip file you've downloaded before, please make sure to extract the winhttp.dll aswell and make sure its in the `Death Must Die` folder.

**Comment by szmit1** [comment]
Seems like it works fine now  tho still 4 stashes like in default game

**Comment by JustArion** [comment]
For the More Stash Tabs mod I may need to do a quick hotfix for having 4 default tabs and everything should be set.

I'll post a .dll release shortly, afterwards let me know if everything works for you.

**Comment by JustArion** [comment]
> Seems like it works fine now tho still 4 stashes like in default game

My latest hotfix should fix that issue, its available [here](https://github.com/JustArion/DeathMustDieMods/releases/download/v1.0.1/MoreStashTabs.dll).

**Comment by szmit1** [comment]
5 stashes works fine

**Comment by JustArion** [comment]
Thats great! let me know if you need any other help and I'll happily try my best to assist.

**Comment by szmit1** [comment]
Thanks man you have a beer from me if we meet somehow. do you have ideas for other mods?

**Comment by JustArion** [comment]
I was considering additional difficulty increases but apart from that any ideas are welcome.

What I mean by difficulty increase options are like, monsters get additional speed and such when using the "Star Crux"

**Comment by szmit1** [comment]
additional option for more chance of higher lv % ofd mawster and leg boons owuld be greate and better item drop rate,  maeby if possible mod that inceased  numbers of enemies and `special ` waves ,  
more elites enemies
longer time before dracula fight? 
More then one boon on lv up ?

**Comment by szmit1** [comment]
maeby more items sets?

**Comment by JustArion** [comment]
> additional option for more chance of higher lv % ofd mawster and leg boons owuld be greate and better item drop rate, maeby if possible mod that inceased numbers of enemies and `special ` waves , more elites enemies longer time before dracula fight? More then one boon on lv up ?

Some of these are definitely possible. I'll look more into making those sometime ^^

**Comment by szmit1** [comment]
:D

**Comment by szmit1** [comment]
![image](https://github.com/JustArion/DeathMustDieMods/assets/154764420/7c5fed5e-54bc-41bd-aad2-f8e737db3959)
 nice

**Comment by JustArion** [comment]
> ![image](https://private-user-images.githubusercontent.com/154764420/292692894-7c5fed5e-54bc-41bd-aad2-f8e737db3959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NjI2MTcsIm5iZiI6MTcwMzQ2MjMxNywicGF0aCI6Ii8xNTQ3NjQ0MjAvMjkyNjkyODk0LTdjNWZlZDVlLTU0YmMtNDFiZC1hYWQyLWY4ZTczN2RiMzk1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQyMzU4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmFlODExZDhjZjczNmMzZmEyNmNhMWM4ZjNmN2E2NzAwODYwNGY5MTM2YWNjM2VmYmNlNWI5Zjc0MmUyY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mU6DzI5aibO-3BdssxgfsaDxQ4bE6mDpXajOd693vGg) nice

Thats for sure a lot of boons! Most likely the #1 things to mod next would be 
- Extending the time between boss fights
- The total game length to more than 20mins
- More "Star Crux" options and higher max levels for them

**Comment by szmit1** [comment]
Noice !

**Comment by szmit1** [comment]
![image](https://github.com/JustArion/DeathMustDieMods/assets/154764420/9dbd94f5-c36b-415e-aed5-efac48c6da21)
 its fun :D
